services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db:3306/app_db
      - POPULATE_DB=1
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/code

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 5

  tests:
    build: 
      context: ./backend
      dockerfile: Dockerfile.test
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db:3306/app_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/code
    restart: "no"

volumes:
  mysql_data: