
FROM python:3.9-slim

ENV PYTHONPATH=/code
WORKDIR /code


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

CMD ["sh", "-c", "echo PYTHONPATH=$PYTHONPATH; echo '---'; ls -l /code; echo '---'; ls -l /code/app; echo '---'; pytest -v app/loja/ app/marca/ app/modelo/ app/pessoa/ app/venda/ app/vendedor/"]